name: build-any

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
  
    name: npm-publish
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run nx run-many -- --target=build --projects=ng-client-demo --configuration=production

    - name: Test
      run: npm run nx run-many -- --target=test --projects=ng-client-demo --watch=false --browsers=ChromeHeadless
